version: '3'

services:

    postgres:
        container_name: postgres
        image: postgres:latest

    redis:
        container_name: redis
        image: redis:latest

    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        depends_on:
            - api
            - client
        ports:
            - 3050:80
    
    client:
        container_name: client
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - ./client:/app
            - /app/node_modules
    
    api:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        depends_on:
            - postgres
            - redis
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        volumes:
            - ./server:/app
            - /app/node_modules

    worker:
        container_name: worker
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - ./worker:/app
            - /app/node_modules